algo = input('Digite algo: ')

print('Alnum?', algo.isalnum())
print('Alpha?', algo.isalpha())
print('Ascii?', algo.isascii())
print('Digit?', algo.isdigit())
print('Lower?', algo.islower())
print('Decimal?', algo.isdecimal())
print('Identifier?', algo.isidentifier())
print('Numeric?', algo.isnumeric())
print('Printable?', algo.isprintable())
print('Space?', algo.isspace())
print('Title?', algo.istitle())
print('Upper?', algo.isupper())